Improvements in scripts to allow "configure;make" to work properly when run in the source directory itself.  Simplified README to point to the autodock README. Modified Files: Makefile.am README copyfilesfromAD
CVS-ID: Makefile.am 1.28
CVS-ID: README 1.5
CVS-ID: copyfilesfromAD 1.4

diff --git a/copyfilesfromAD b/copyfilesfromAD
--- a/copyfilesfromAD
+++ b/copyfilesfromAD
@@ -5,24 +5,32 @@
 # remove local AutoGrid versions of key source files shared with AutoDock,
 #  replacing them with copies from ../autodock
 # 
-# option -b   : is being run from build dir rather src dir
 # option -r   : removes these files, does not copy 
 #
-# $Id: copyfilesfromAD,v 1.3 2012/11/01 22:17:05 rhuey Exp $
+# $Id: copyfilesfromAD,v 1.4 2013/02/26 23:58:01 mp Exp $
 #
 # M Pique
 
-prefix=".."  # where 'autodock' dir is from src dir
-if [ test$1 = test-b ]; then
-   prefix="../.."  # where 'autodock' dir is from build dir
-fi
 
 copy=y
 if [ test$1 = test-r ]; then
   copy=n
+else
+  #
+  # determine where 'autodock' source files are: 
+  # in ../autodock or ../../autodock
+  # by searching for stop.cc source file there
+  #
+  if [ -r ../autodock/stop.cc ]; then
+    srcdir=".."  # where 'autodock' dir is from build dir
+  elif [ -r ../../autodock/stop.cc ]; then
+    srcdir="../.."  # where 'autodock' dir is from build dir
+  else
+    echo "cannot locate autodock source directory"
+    exit 1
+  fi
 fi
 
-DO="ln -s"
 DO="cp -p"
 
 # .cpp and .h if present in ../autodock
@@ -39,7 +47,8 @@ for c in  \
 	timesyshms \
   ; do
    rm -f $c.cpp $c.h
-   test $copy = y && test -r ${prefix}/autodock/$c.cc && $DO  ${prefix}/autodock/$c.cc $c.cpp
-   test $copy = y && test -r ${prefix}/autodock/$c.h && $DO  ${prefix}/autodock/$c.h  $c.h
+   test $copy = y && test -r ${srcdir}/autodock/$c.cc && $DO  ${srcdir}/autodock/$c.cc $c.cpp
+   test $copy = y && test -r ${srcdir}/autodock/$c.h && $DO  ${srcdir}/autodock/$c.h  $c.h
 done
+exit 0
 
